version: 0.2
env:
  secrets-manager:
    DOCKER_ID: "docker-credentials:docker_id"
    DOCKER_PW: "docker-credentials:docker_token"
phases:
  pre_build:
    commands:
    - echo Logging in to the Docker CLI
    - echo $DOCKER_PW | docker login -u $DOCKER_ID --password-stdin
    - REPOSITORY_NAME="barbak-$STAGE_NAME"
  build:
    commands:
    - echo Building Docker images
    - echo Build started on `date`
    - docker build -t reyhec/$REPOSITORY_NAME-webserver ./webserver
    - docker build -t reyhec/$REPOSITORY_NAME-client ./client
    - docker build -t reyhec/$REPOSITORY_NAME-backend ./backend
  post_build:
    commands:
    - echo Pushing images to Docker Hub
    - docker push reyhec/$REPOSITORY_NAME-webserver
    - docker push reyhec/$REPOSITORY_NAME-client
    - docker push reyhec/$REPOSITORY_NAME-backend
artifacts:
  files:
    - '**/*'

# Resource:
  # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html