version: 0.2
env:
  secrets-manager:
    DOCKER_ID: "barbak-build-secrets:docker_id"
    DOCKER_PW: "barbak-build-secrets:docker_access_token"
phases:
  build:
    commands:
    - echo Build started on `date`
    # Build the Docker images
    - echo Building the production Docker images...
    - docker build -t reyhec/barbak-webserver ./webserver
    - docker build -t reyhec/barbak-client ./client
    - docker build -t reyhec/barbak-backend ./backend
    # Log In to the Docker CLI
    - echo $DOCKER_PW | docker login -u $DOCKER_ID --password-stdin
  post_build:
    commands:
    # Take these images and push them to Docker hub
    - echo Pushing to Docker images...
    - docker push reyhec/barbak-webserver
    - docker push reyhec/barbak-client
    - docker push reyhec/barbak-backend
artifacts:
  files:
    - '**/*'