version: '3'
services:
  webserver:
    container_name: webserver
    depends_on:
      - barbak_client
      - barbak_backend
      - api_client
      - api_backend
    build:
      dockerfile: Dockerfile
      context: ./webserver
    restart: always # because it is routing traffic to our entire app
    ports:
      - 80:80
    
  barbak_client:
    container_name: barbak_client
    build:
      dockerfile: Dockerfile
      context: ./barbak_client
    restart: on-failure
    volumes:
      - /app/node_modules
    
  barbak_backend:
    container_name: barbak_backend
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
      context: ./barbak_backend
    restart: on-failure
    volumes:
      - /app/node_modules
      - assets:/app/assets
    env_file:
      - ./barbak_backend/env/webhost.env
    
  api_client:
    container_name: api_client
    build:
      dockerfile: Dockerfile
      context: ./api_client
    restart: on-failure
    volumes:
      - /app/node_modules
    
  api_backend:
    container_name: api_backend
    depends_on: 
      - mongo
    build:
      dockerfile: Dockerfile
      context: ./api_backend
    restart: on-failure
    volumes:
      - /app/node_modules
      - assets:/app/assets
    env_file:
      - ./api_backend/env/webhost.env
      
  mongo:
    container_name: mongo
    image: 'mongo'
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db


volumes:
  assets: