version: '3'
services:
  webserver:
    container_name: webserver
    build:
      dockerfile: Dockerfile
      context: ./webserver
    restart: always # because it is routing traffic to our entire app
    ports:
      - 80:80 # setting port because nginx is the single entrypoint for entire application

  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: on-failure
    env_file: ./env/client/production.env
  
  backend:
    container_name: backend
    depends_on:
      - mongo
      - mysql
      - redis
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: on-failure
    env_file:
      - ./env/backend/production.env

  mongo:
    container_name: mongo
    image: mongo:latest
    env_file:
      - ./env/database/mongo/production.env
    volumes:
      - ./database/mongo/init/roles.js:/docker-entrypoint-initdb.d/roles.js:ro

  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql/init/barware.sql:/docker-entrypoint-initdb.d/init-barware.sql:ro
      - ./database/mysql/init/permissions.sql:/docker-entrypoint-initdb.d/init-permissions.sql:ro
    env_file:
      - ./env/database/mysql/production.env

  redis:
    container_name: redis
    image: redis:latest